### ISSUE TITLE
frontpage scrollable

### ISSUE THREAD

**Issue by violoncelloch** [Pastheme/pagekit-bcs#1]
the viewport heigth container excludes the navbar, so the frontpage is scrollable as height as the navbar is even though it shouldn't...
maybe this could be fixed easily by creating a viewport height-container around the navbar and the content... should I create a PR for this?

**Comment by Bigchefstarys** [comment]
It will be updated to a later version. What is PR?

**Comment by violoncelloch** [comment]
Ok thank you!
A PR is a pull request to the git repository...

**Comment by Bigchefstarys** [comment]
@violoncelloch thank you ;)

**Comment by violoncelloch** [comment]
as #2 is merged, could you create a new release (1.0.1) and update it in the pagekit marketplace? :)

**Comment by Bigchefstarys** [comment]
@violoncelloch I updated the files now. Thank you

**Comment by violoncelloch** [comment]
Thank you very much!
